import type { Instrument, InstrumentAlias } from "@portfolio-atlas/contracts";
import { fixtureTime } from "./mandate-fixtures.js";

const alias = (
  symbol: string,
  listingId: string,
  from: string,
  to: string | null,
): InstrumentAlias => ({
  assertionId: "alias-" + symbol,
  revision: 1,
  provider: "synthetic",
  symbol,
  venueMic: "XNAS",
  listingId,
  validFrom: from,
  validTo: to,
  observedAt: "2025-01-01T00:00:00Z",
  availableAt: "2025-01-01T00:00:00Z",
  evidenceSource: "SYNTHETIC listing notice",
});
export const syntheticInstruments: Instrument[] = [
  {
    instrumentId: "DEMO-AURORA",
    listingId: "DEMO-AURORA-US",
    issuerId: "DEMO-ISSUER-AURORA",
    name: "Aurora Systems · US common",
    revision: 1,
    requestedSymbol: "AURA",
    returnedSymbol: "AURA",
    source: "synthetic",
    observedAt: fixtureTime,
    quoteTime: fixtureTime,
    observedVenue: "Synthetic Nasdaq venue",
    venueMic: "XNAS",
    timezone: "America/New_York",
    quoteUnit: {
      reported: "USD",
      currency: "USD",
      scaleToCurrency: 1,
      evidence: "Synthetic listing contract: USD per share.",
    },
    assetType: "equity",
    sector: "TECHNOLOGY",
    tickSize: 0.01,
    lotSize: 1,
    tradingUnitEvidence: "SYNTHETIC venue rulebook v1",
    identityStatus: "synthetic_verified",
    aliases: [
      alias("AUR-OLD", "DEMO-AURORA-US", "2025-01-01T00:00:00Z", "2026-01-01T00:00:00Z"),
      alias("AURA", "DEMO-AURORA-US", "2026-01-01T00:00:00Z", null),
    ],
    warnings: ["Fictional security and fictional venue evidence for teaching."],
  },
  {
    instrumentId: "DEMO-AURORA-GB",
    listingId: "DEMO-AURORA-GB-LINE",
    issuerId: "DEMO-ISSUER-AURORA",
    name: "Aurora Systems · UK preferred",
    revision: 1,
    requestedSymbol: "AURA.L",
    returnedSymbol: "AURA.L",
    source: "synthetic",
    observedAt: fixtureTime,
    quoteTime: fixtureTime,
    observedVenue: "Synthetic London venue",
    venueMic: "XLON",
    timezone: "Europe/London",
    quoteUnit: {
      reported: "GBp",
      currency: "GBP",
      scaleToCurrency: 0.01,
      evidence: "Synthetic listing contract: pence per share; 100 pence = GBP 1.",
    },
    assetType: "equity",
    sector: "TECHNOLOGY",
    tickSize: null,
    lotSize: null,
    tradingUnitEvidence: null,
    identityStatus: "synthetic_verified",
    aliases: [],
    warnings: [
      "Same issuer does not prove equal rights or fungibility.",
      "Trading-unit evidence is missing.",
    ],
  },
  {
    instrumentId: "DEMO-HARBOR",
    listingId: "DEMO-HARBOR-US",
    issuerId: "DEMO-ISSUER-HARBOR",
    name: "Harbor Health",
    revision: 1,
    requestedSymbol: "HARB",
    returnedSymbol: "HARB",
    source: "synthetic",
    observedAt: fixtureTime,
    quoteTime: fixtureTime,
    observedVenue: "Synthetic Nasdaq venue",
    venueMic: "XNAS",
    timezone: "America/New_York",
    quoteUnit: {
      reported: "USD",
      currency: "USD",
      scaleToCurrency: 1,
      evidence: "Synthetic listing contract: USD per share.",
    },
    assetType: "equity",
    sector: "HEALTHCARE",
    tickSize: 0.01,
    lotSize: 1,
    tradingUnitEvidence: "SYNTHETIC venue rulebook v1",
    identityStatus: "synthetic_verified",
    aliases: [alias("HARB", "DEMO-HARBOR-US", "2025-01-01T00:00:00Z", null)],
    warnings: ["Fictional security."],
  },
  {
    instrumentId: "DEMO-INDEX",
    listingId: "DEMO-INDEX-US",
    issuerId: null,
    name: "Atlas Broad ETF",
    revision: 1,
    requestedSymbol: "ATLS",
    returnedSymbol: "ATLS",
    source: "synthetic",
    observedAt: fixtureTime,
    quoteTime: fixtureTime,
    observedVenue: "Synthetic Nasdaq venue",
    venueMic: "XNAS",
    timezone: "America/New_York",
    quoteUnit: {
      reported: "USD",
      currency: "USD",
      scaleToCurrency: 1,
      evidence: "Synthetic listing contract: USD per ETF share.",
    },
    assetType: "etf",
    sector: "DIVERSIFIED FUND",
    tickSize: 0.01,
    lotSize: 1,
    tradingUnitEvidence: "SYNTHETIC venue rulebook v1",
    identityStatus: "synthetic_verified",
    aliases: [alias("ATLS", "DEMO-INDEX-US", "2025-01-01T00:00:00Z", null)],
    warnings: ["Sector is a fund classification, not constituent look-through."],
  },
];
export const syntheticAliases = syntheticInstruments.flatMap((instrument) => instrument.aliases);
